export const CustomerTransactionList = [
 { id: 1, customerName: "Adam Sam", imgUrl: "image001.jpg", date: "19 Jun 2021", amount: "$1561.00", statusType: "Approved" },
 { id: 2, customerName: "John David", imgUrl: "image003.jpg", date: "27 Feb 2021", amount: "$3018.00", statusType: "Pending" },
 { id: 3, customerName: "Cecilia Pratt", imgUrl: "image004.jpg", date: "9 Dec 2021", amount: "$4416.00", statusType: "Declined" },
 { id: 4, customerName: "Sarah Miles", imgUrl: "image003.jpg", date: "21 Nov 2021", amount: "$959.00", statusType: "Approved" },
 { id: 5, customerName: "Martin Woods", imgUrl: "image003.jpg", date: "3 Jan 2021", amount: "$3154.00", statusType: "Approved" },
 { id: 6, customerName: "Don Hunt", imgUrl: "image002.jpg", date: "21 May 2021", amount: "$1032.00", statusType: "Declined" },
 { id: 7, customerName: "Hettie Montgomery", imgUrl: "image004.jpg", date: "1 Jun 2021", amount: "$3176.00", statusType: "Approved" },
 { id: 8, customerName: "Carrie Cole", imgUrl: "image001.jpg", date: "29 April 2021", amount: "$2800.00", statusType: "Pending" },
 { id: 9, customerName: "Jay Drake", imgUrl: "image001.jpg", date: "29 April 2019", amount: "$2800.00", statusType: "Declined" },
 { id: 10, customerName: "Steven Luna", imgUrl: "image003.jpg", date: "11 June 2020", amount: "$2800.00", statusType: "Pending" },
 { id: 11, customerName: "Marvin Larson", imgUrl: "image004.jpg", date: "29 April 2021", amount: "$2800.00", statusType: "Declined" },
 { id: 12, customerName: "Wayne Bryan", imgUrl: "image003.jpg", date: "29 Sep 2021", amount: "$2800.00", statusType: "Pending" },
 { id: 13, customerName: "Helen Knight", imgUrl: "image001.jpg", date: "29 April 2019", amount: "$2800.00", statusType: "Approved" },
 { id: 14, customerName: "Robert Hale", imgUrl: "image002.jpg", date: "29 March 2020", amount: "$2800.00", statusType: "Declined" },
 { id: 15, customerName: "John Neal", imgUrl: "image004.jpg", date: "29 April 2019", amount: "$2800.00", statusType: "Approved" },
]

export const SalesData = [
  {
    name: 'Jan',
    sales: 4120,
    amount: 1000
  },
  {
    name: 'Feb',
    sales: 3200,
    amount: 2000
  },
  {
    name: 'Mar',
    sales: 2000,
    amount: 3000
  },
  {
    name: 'April',
    sales: 2780,
    amount: 4000
  },
  {
    name: 'May',
    sales: 1890,
    amount: 5000
  },
  {
    name: 'June',
    sales: 2390,
    amount: 6000
  },
  {
    name: 'July',
    sales: 3490,
    amount: 7000
  },
  {
    name: 'Aug',
    sales: 2490,
    amount: 8000
  },
  {
    name: 'Sep',
    sales: 5050,
    amount: 9000
  },
  {
    name: 'Oct',
    sales: 4500,
    amount: 10000
  },
  {
    name: 'Nov',
    sales: 5200,
    amount: 11000
  },
  {
    name: 'Dec',
    sales: 8600,
    amount: 12000
  },
];

export const productData = [
  {
    name: "Jan",
    "Sales": 4000,
  },
  {
    name: "Feb",
    "Sales": 3000,
  },
  {
    name: "Mar",
    "Sales": 5000,
  },
  {
    name: "Apr",
    "Sales": 6000,
  },
  {
    name: "May",
    "Sales": 1000,
  },
];

export const EmployeeList = [
  { id: 1, EmployeeName: "Adam Sam", EmployeeTitle: "Developer", imgUrl: "image001.jpg" },
  { id: 2, EmployeeName: "William Frank", EmployeeTitle: "Sales", imgUrl: "image002.jpg" },
  { id: 3, EmployeeName: "Sally Rose", EmployeeTitle: "Marketing", imgUrl: "image003.jpg" },
  { id: 4, EmployeeName: "Tom Harvey", EmployeeTitle: "Customer Service", imgUrl: "image004.jpg" },
  { id: 5, EmployeeName: "Stanley Salazar", EmployeeTitle: "Customer Service", imgUrl: "image004.jpg" },
  { id: 6, EmployeeName: "Jane Samuel", EmployeeTitle: "Assistant Manager", imgUrl: "image001.jpg" },
  { id: 7, EmployeeName: "Esther Mann", EmployeeTitle: "Assistant Manager", imgUrl: "image001.jpg" },
  { id: 8, EmployeeName: "Stanley Schultz", EmployeeTitle: "Assistant Manager", imgUrl: "image001.jpg" },
  { id: 9, EmployeeName: "Kevin Chavez", EmployeeTitle: "Assistant Manager", imgUrl: "image001.jpg" },
  { id: 10, EmployeeName: "Nora Fuller", EmployeeTitle: "Assistant Manager", imgUrl: "image001.jpg" }
]

export const UserRowData = [
 { id: 1, username: "Matthew Reese", email: "jownic@sa.tm", imgUrl: "image001.jpg", status: "Active", transaction: "$257.00" },
 { id: 2, username: "Irene Sandoval", email: "inkabon@tebefotob.us", imgUrl: "image002.jpg", status: "Active", transaction: "$637.00" },
 { id: 3, username: "Brent Parsons", email: "mehwocbe@tirigaje.gh", imgUrl: "image003.jpg", status: "Active", transaction: "$651.00" },
 { id: 4, username: "Jerry Flowers", email: "ivapac@ju.it", imgUrl: "image001.jpg", status: "Decline", transaction: "$494.00" },
 { id: 5, username: "Lina Sims", email: "mogide@zano.fo", imgUrl: "image004.jpg", status: "Active", transaction: "$797.00" },
 { id: 6, username: "Steven Francis", email: "buvme@uc.hm", imgUrl: "image001.jpg", status: "Active", transaction: "$394.00" },
 { id: 7, username: "Viola Garza", email: "fi@sihpufi.bz", imgUrl: "image002.jpg", status: "Active", transaction: "$367.00" },
 { id: 8, username: "Nina Perez", email: "ta@guhe.yt", imgUrl: "image003.jpg", status: "Active", transaction: "$491.00" },
 { id: 9, username: "Julia Rios", email: "pomvajwev@sili.va", imgUrl: "image001.jpg", status: "Decline", transaction: "$549.00" },
 { id: 10, username: "Luis Spencer", email: "ohubos@ig.ci", imgUrl: "image002.jpg", status: "Active", transaction: "$348.00" },
 { id: 11, username: "Cora Cook", email: "tum@buogcu.bh", imgUrl: "image004.jpg", status: "Active", transaction: "$598.00" },
 { id: 12, username: "Jayden Copeland", email: "wud@potomu.gt", imgUrl: "image002.jpg", status: "Active", transaction: "$322.00" },
 { id: 13, username: "Marc Pittman", email: "heh@upmika.gr", imgUrl: "image003.jpg", status: "Active", transaction: "$205.00" },
 { id: 14, username: "Steve Miles", email: "mu@sogivi.er", imgUrl: "image001.jpg", status: "Active", transaction: "$300.00" },
 { id: 15, username: "Winnie Ramos", email: "gufbezi@bum.mr", imgUrl: "image002.jpg", status: "Decline", transaction: "$568.00" },
 { id: 16, username: "Cory Ramsey", email: "do@ojiwu.ms", imgUrl: "image003.jpg", status: "Active", transaction: "$321.00" },
 { id: 17, username: "Etta Little", email: "je@bitufiit.nf", imgUrl: "image001.jpg", status: "Decline", transaction: "$706.00" },
 { id: 18, username: "Delia Cobb", email: "nokafves@cusilese.in", imgUrl: "image002.jpg", status: "Active", transaction: "$638.00" },
 { id: 19, username: "Eric Bates", email: "ocgobo@wupu.ae", imgUrl: "image004.jpg", status: "Decline", transaction: "$645.00" },
 { id: 20, username: "Donald Long", email: "kukimadew@zor.ir", imgUrl: "image002.jpg", status: "Active", transaction: "$597.00" },
 { id: 21, username: "Cecilia Jackson", email: "bav@ab.rw", imgUrl: "image001.jpg", status: "Decline", transaction: "$341.00" },
 { id: 22, username: "Teresa Williamson", email: "zozomaj@okuheb.na", imgUrl: "image003.jpg", status: "Active", transaction: "$620.00" },
 { id: 23, username: "Stanley Ford", email: "misheheji@bijol.sx", imgUrl: "image004.jpg", status: "Active", transaction: "$508.00" },
 { id: 24, username: "Cornelia Barton", email: "ceftiw@faesu.gi", imgUrl: "image002.jpg", status: "Active", transaction: "$192.00" },
 { id: 25, username: "Ella Watts", email: "vul@nociril.jp", imgUrl: "image001.jpg", status: "Active", transaction: "$369.00" },
]

export const countryList = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas (the)",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia (Plurinational State of)",
	"Bonaire, Sint Eustatius and Saba",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"Brazil",
	"British Indian Ocean Territory (the)",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cayman Islands (the)",
	"Central African Republic (the)",
	"Chad",
	"Chile",
	"China",
	"Christmas Island",
	"Cocos (Keeling) Islands (the)",
	"Colombia",
	"Comoros (the)",
	"Congo (the Democratic Republic of the)",
	"Congo (the)",
	"Cook Islands (the)",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Curaçao",
	"Cyprus",
	"Czechia",
	"Côte d'Ivoire",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic (the)",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Falkland Islands (the) [Malvinas]",
	"Faroe Islands (the)",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories (the)",
	"Gabon",
	"Gambia (the)",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See (the)",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea (the Democratic People's Republic of)",
	"Korea (the Republic of)",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic (the)",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands (the)",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia (Federated States of)",
	"Moldova (the Republic of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands (the)",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger (the)",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands (the)",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine, State of",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines (the)",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Republic of North Macedonia",
	"Romania",
	"Russian Federation (the)",
	"Rwanda",
	"Réunion",
	"Saint Barthélemy",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Martin (French part)",
	"Saint Pierre and Miquelon",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Sint Maarten (Dutch part)",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia and the South Sandwich Islands",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan (the)",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Taiwan",
	"Tajikistan",
	"Tanzania, United Republic of",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands (the)",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates (the)",
	"United Kingdom of Great Britain and Northern Ireland (the)",
	"United States Minor Outlying Islands (the)",
	"United States of America (the)",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela (Bolivarian Republic of)",
	"Viet Nam",
	"Virgin Islands (British)",
	"Virgin Islands (U.S.)",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Åland Islands"
];

export const productRows = [
  {
    id: 1,
    name: "Iphone 13",
    imgUrl:
      "iphone13.jpg",
    stock: 291,
    status: "In Stock",
    price: "$120.00",
  },
  {
    id: 2,
    name: "Iphone 13",
    imgUrl:
      "iphone13.jpg",
    stock: 414,
    status: "In Stock",
    price: "$120.00",
  },
  {
    id: 3,
    name: "Iphone 13",
    imgUrl:
      "iphone13.jpg",
    stock: 431,
    status: "In Stock",
    price: "$120.00",
  },
  {
    id: 4,
    name: "Iphone 13",
    imgUrl:
      "iphone13.jpg",
    stock: 0,
    status: "Out of Stock",
    price: "$120.00",
  },
  {
    id: 5,
    name: "Iphone 13",
    imgUrl:
      "iphone13.jpg",
    stock: 0,
    status: "Out of Stock",
    price: "$120.00",
  },
  {
    id: 6,
    name: "Iphone 13",
    imgUrl:
      "iphone13.jpg",
    stock: 368,
    status: "In Stock",
    price: "$120.00",
  },
  {
    id: 7,
    name: "Iphone 13",
    imgUrl:
      "iphone13.jpg",
    stock: 0,
    status: "Out of Stock",
    price: "$120.00",
  },
  {
    id: 8,
    name: "Iphone 13",
    imgUrl:
      "iphone13.jpg",
    stock: 324,
    status: "In Stock",
    price: "$120.00",
  },
  {
    id: 9,
    name: "Iphone 13",
    imgUrl:
      "iphone13.jpg",
    stock: 0,
    status: "Out of Stock",
    price: "$120.00",
  },
  {
    id: 10,
    name: "Iphone 13",
    imgUrl:
      "iphone13.jpg",
    stock: 229,
    status: "In Stock",
    price: "$120.00",
  },
];